### ISSUE TITLE
Update to ML.NET 1.0.0

### ISSUE THREAD

**Issue by developervariety** [CESARDELATORRE/TensorFlowImageClassificationWebAPI#1]
I am trying to use my own TF model with your work with ML.NET 1.0.0 and I'm having trouble with the input names etc.

**Comment by CESARDELATORRE** [comment]
Try opening the TF .pb model with Netron to see the input names of your particular model, etc.

https://electronjs.org/apps/netron

Closing this issue since it is not related with our samples' code, ok?

**Comment by developervariety** [comment]
Hi @CESARDELATORRE, thank you for the response.

I put the correct names, and now it is working somewhat. I am not sure why I need to put a label in the TSV file if I want the model get the best match.

Am I not supposed to use ImageClassification and use TFEstimator sample?

**Comment by CESARDELATORRE** [comment]
TFEstimator sample is more complex and is meant to be used if you want to do a TRAINING (such as an additional multi-class classification) in ML.NET "on top" of the TensorFlow model. This is kind of known as "Transfer Learning".

If you just want to run/score predictions with a TensorFlow model, then it is like this sample.

**Comment by CESARDELATORRE** [comment]
Although the way I'm running this WEB API sample is not optimized (it is an old sample).
See how we run ML.NET models in an optimized way in this other sample:

https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/end-to-end-apps/ScalableMLModelOnWebAPI-IntegrationPkg

That sample is using the new "ASP.NET Integration package" for ML.NET: 

Microsoft.Extension.ML

Which provides a pool of PredictionEngine objects, optimized for scalable and multi-threaded ASP.NET Core web apps.
